services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
      - ./ml/data:/data
      - ./ml/models:/models
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/elearning_db
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    
  # Dịch vụ Frontend (UI)
  frontend:
    build: ./frontend
    ports:
      - "3000:80" # Mapping port của NGINX
    depends_on:
      - backend
      
  # Dịch vụ Cơ sở dữ liệu
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/ # Dùng volume để giữ dữ liệu
      - ./database/schema.sql:/docker-entrypoint-initdb.d/init.sql # Tự động chạy schema
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=elearning_db
    ports:
      - "5432:5432" # Mở port ra ngoài để có thể debug bằng pgAdmin

volumes:
  postgres_data: # Khai báo volume